# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

parameters:
  - name: changeNumber
    type: string
    default: null

trigger:
- master


  
stages:
- stage: build
  jobs:
  - job: 'BuildAndPush'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: echo Hello, world!
    displayName: 'Run a one-line script'
  - job: 'push'
    steps:
    - script: echo Add other tasks to build, test, and deploy $(Username)

- stage: deploy
  jobs:
    - job : 'deploy'
  
