# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

parameters:
  - name: changeNumber
    type: string
    default: null

trigger:
- master


  
stages:
- stage: build
  jobs:
  - job: 'BuildAndPush'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: echo build
    displayName: 'Running build'
  - job: 'push'
    steps:
    - script: echo push

- stage: deploy
  jobs:
  - deployment: 
    pool:
      vmImage: 'ubuntu-latest'
    environment: Test
    strategy:
     runOnce:
       deploy:
         steps:
           - script: echo deploy
